ALTER TABLE IF EXISTS matches
ALTER COLUMN id TYPE BYTEA USING id::BYTEA;
ALTER TABLE IF EXISTS matches
ALTER COLUMN matcher_id TYPE BYTEA USING id::BYTEA;
ALTER TABLE IF EXISTS matches
ALTER COLUMN matchee_id TYPE BYTEA USING id::BYTEA;