version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: studiumz_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PWD
    volumes:
      - studiumz_db:/var/lib/postgresql/data
    ports:
      - $DB_HOST:$DB_PORT:5432

volumes:
  studiumz_db:
